// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.8
// source: datafeed/proto/operator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportOutcomeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market  string `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Outcome string `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *ReportOutcomeReq) Reset() {
	*x = ReportOutcomeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datafeed_proto_operator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportOutcomeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportOutcomeReq) ProtoMessage() {}

func (x *ReportOutcomeReq) ProtoReflect() protoreflect.Message {
	mi := &file_datafeed_proto_operator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportOutcomeReq.ProtoReflect.Descriptor instead.
func (*ReportOutcomeReq) Descriptor() ([]byte, []int) {
	return file_datafeed_proto_operator_proto_rawDescGZIP(), []int{0}
}

func (x *ReportOutcomeReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *ReportOutcomeReq) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type ReportOutcomeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketHash string `protobuf:"bytes,1,opt,name=marketHash,proto3" json:"marketHash,omitempty"`
}

func (x *ReportOutcomeResp) Reset() {
	*x = ReportOutcomeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datafeed_proto_operator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportOutcomeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportOutcomeResp) ProtoMessage() {}

func (x *ReportOutcomeResp) ProtoReflect() protoreflect.Message {
	mi := &file_datafeed_proto_operator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportOutcomeResp.ProtoReflect.Descriptor instead.
func (*ReportOutcomeResp) Descriptor() ([]byte, []int) {
	return file_datafeed_proto_operator_proto_rawDescGZIP(), []int{1}
}

func (x *ReportOutcomeResp) GetMarketHash() string {
	if x != nil {
		return x.MarketHash
	}
	return ""
}

var File_datafeed_proto_operator_proto protoreflect.FileDescriptor

var file_datafeed_proto_operator_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x22, 0x44, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x11, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x32, 0x50,
	0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x46, 0x65, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datafeed_proto_operator_proto_rawDescOnce sync.Once
	file_datafeed_proto_operator_proto_rawDescData = file_datafeed_proto_operator_proto_rawDesc
)

func file_datafeed_proto_operator_proto_rawDescGZIP() []byte {
	file_datafeed_proto_operator_proto_rawDescOnce.Do(func() {
		file_datafeed_proto_operator_proto_rawDescData = protoimpl.X.CompressGZIP(file_datafeed_proto_operator_proto_rawDescData)
	})
	return file_datafeed_proto_operator_proto_rawDescData
}

var file_datafeed_proto_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datafeed_proto_operator_proto_goTypes = []interface{}{
	(*ReportOutcomeReq)(nil),  // 0: v1.ReportOutcomeReq
	(*ReportOutcomeResp)(nil), // 1: v1.ReportOutcomeResp
}
var file_datafeed_proto_operator_proto_depIdxs = []int32{
	0, // 0: v1.DataFeedOperator.ReportOutcome:input_type -> v1.ReportOutcomeReq
	1, // 1: v1.DataFeedOperator.ReportOutcome:output_type -> v1.ReportOutcomeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datafeed_proto_operator_proto_init() }
func file_datafeed_proto_operator_proto_init() {
	if File_datafeed_proto_operator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datafeed_proto_operator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportOutcomeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datafeed_proto_operator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportOutcomeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datafeed_proto_operator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datafeed_proto_operator_proto_goTypes,
		DependencyIndexes: file_datafeed_proto_operator_proto_depIdxs,
		MessageInfos:      file_datafeed_proto_operator_proto_msgTypes,
	}.Build()
	File_datafeed_proto_operator_proto = out.File
	file_datafeed_proto_operator_proto_rawDesc = nil
	file_datafeed_proto_operator_proto_goTypes = nil
	file_datafeed_proto_operator_proto_depIdxs = nil
}
